export const ATypes = {
  // Register
  REGISTRY_SUBMITTED: 'REGISTRY_SUBMITTED',
  REGISTRY_SUCCESS: 'REGISTRY_SUCCESS',
  REGISTRY_FAILED: 'REGISTRY_FAILED',
  // Register
  LOGIN_SUBMITTED: 'LOGIN_SUBMITTED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  // Error Handling
  POST_ERROR: 'POST_ERROR',
  GET_ERROR: 'GET_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
}